// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  // Configuración para Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2lHyFVQhey6C1Dib1mDBijVGopWvvhGg',
    appId: '1:1234567890:web:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'rappitaxi-app',
    authDomain: 'rappitaxi-app.firebaseapp.com',
    storageBucket: 'rappitaxi-app.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  // Configuración para Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2lHyFVQhey6C1Dib1mDBijVGopWvvhGg',
    appId: '1:1234567890:android:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'rappitaxi-app',
    storageBucket: 'rappitaxi-app.appspot.com',
  );

  // Configuración para iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2lHyFVQhey6C1Dib1mDBijVGopWvvhGg',
    appId: '1:1234567890:ios:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'rappitaxi-app',
    storageBucket: 'rappitaxi-app.appspot.com',
    iosBundleId: 'com.rappitaxi.app',
  );
}